// ============================================================================
// Module: imprinted_embedding_rom
// Description: Hardwired embedding generator for optional imprint profiles.
//
// Profile IDs:
//   2'b01: mini-gpt-hc1-v1 (aligned with current mini-model deterministic setup)
//   2'b10: gemma3-270m-export-v1 (ROM image produced by scripts/export_gemma3_imprint.py)
//
// Notes:
// - This module is additive and only used when imprint mode is enabled by flags.
// - MINI profile is deterministic/formula-based.
// - GEMMA profile reads exported token/position ROM images.
// ============================================================================
`timescale 1ns / 1ps

module imprinted_embedding_rom #(
    parameter DIM        = 8,
    parameter DATA_WIDTH = 16,
    parameter GEMMA_TOKEN_COUNT = 256,
    parameter GEMMA_POS_COUNT   = 64,
    parameter GEMMA_TOKEN_HEX   = "weights/imprint/gemma3_270m_token_emb_q88.hex",
    parameter GEMMA_POS_HEX     = "weights/imprint/gemma3_270m_pos_emb_q88.hex"
)(
    input  wire [15:0]                   token_id,
    input  wire [15:0]                   position,
    input  wire [1:0]                    profile_sel,
    output reg  [DIM*DATA_WIDTH-1:0]     embedding_out,
    output reg                           profile_supported
);

    localparam integer GEMMA_TOKEN_DEPTH = GEMMA_TOKEN_COUNT * DIM;
    localparam integer GEMMA_POS_DEPTH   = GEMMA_POS_COUNT * DIM;

    reg signed [DATA_WIDTH-1:0] gemma_token_rom [0:GEMMA_TOKEN_DEPTH-1];
    reg signed [DATA_WIDTH-1:0] gemma_pos_rom   [0:GEMMA_POS_DEPTH-1];

    integer init_i;
    integer d;
    integer token_slot;
    integer pos_slot;
    integer token_rom_idx;
    integer pos_rom_idx;
    reg signed [31:0] value_calc_s;
    reg [31:0] d_u32;

    initial begin
        for (init_i = 0; init_i < GEMMA_TOKEN_DEPTH; init_i = init_i + 1)
            gemma_token_rom[init_i] = {DATA_WIDTH{1'b0}};
        for (init_i = 0; init_i < GEMMA_POS_DEPTH; init_i = init_i + 1)
            gemma_pos_rom[init_i] = {DATA_WIDTH{1'b0}};

        $readmemh(GEMMA_TOKEN_HEX, gemma_token_rom);
        $readmemh(GEMMA_POS_HEX, gemma_pos_rom);
    end

    always @(token_id or position or profile_sel) begin
        embedding_out     = {DIM*DATA_WIDTH{1'b0}};
        case (profile_sel)
            2'b01, 2'b10: profile_supported = 1'b1;
            default:      profile_supported = 1'b0;
        endcase

        for (d = 0; d < DIM; d = d + 1) begin
            d_u32 = d[31:0];
            value_calc_s = 32'sd0;
            case (profile_sel)
                // Matches the mini-model table generation used in full_model_inference_tb:
                // token = token_id*50 + d*30 + 10
                // pos   = position*20 + d*10
                // sum   = token_id*50 + position*20 + d*40 + 10
                2'b01: begin
                    value_calc_s = $signed(
                        ({16'd0, token_id} * 32'd50) +
                        ({16'd0, position} * 32'd20) +
                        (d_u32 * 32'd40) + 32'd10
                    );
                end

                // Exported Gemma imprint profile.
                // Token/position rows are generated by scripts/export_gemma3_imprint.py.
                2'b10: begin
                    token_slot   = (token_id < GEMMA_TOKEN_COUNT) ? token_id : (GEMMA_TOKEN_COUNT - 1);
                    pos_slot     = (position < GEMMA_POS_COUNT) ? position : (GEMMA_POS_COUNT - 1);
                    token_rom_idx = token_slot * DIM + d;
                    pos_rom_idx   = pos_slot * DIM + d;
                    value_calc_s = $signed(gemma_token_rom[token_rom_idx]) +
                                   $signed(gemma_pos_rom[pos_rom_idx]);
                end

                default: begin
                    value_calc_s = 32'sd0;
                end
            endcase

            embedding_out[d*DATA_WIDTH +: DATA_WIDTH] = value_calc_s[DATA_WIDTH-1:0];
        end
    end

endmodule

