// ============================================================================
// Module: exp_lut_256
// Description: 256-entry lookup table for exp() approximation.
//
//   Formula: LUT[k] = round(255 * exp(-k/64))
//   Range:   k=0 → exp(0) = 255,  k=255 → exp(-3.98) = 5
//
//   Generated by Python:
//     [max(1, min(255, round(255 * math.exp(-k/64.0)))) for k in range(256)]
//
//   The input x_in is Q8.8 signed (expected <= 0 after max-subtraction).
//   Index = clamp(-x_in >> 2, 0, 255)
//   This maps Q8.8 range [-4.0, 0] → LUT index [0, 255]
// ============================================================================
`timescale 1ns / 1ps

module exp_lut_256 (
    input  wire signed [15:0] x_in,    // Q8.8 input (expected <= 0)
    output wire        [7:0]  exp_out  // Q0.8 output [1,255]
);

    reg [7:0] lut [0:255];

    // All values generated by: round(255 * exp(-k/64)) for k=0..255
    // Verified via Python math.exp — no manual approximation
    initial begin
        lut[  0] = 255; lut[  1] = 251; lut[  2] = 247; lut[  3] = 243;
        lut[  4] = 240; lut[  5] = 236; lut[  6] = 232; lut[  7] = 229;
        lut[  8] = 225; lut[  9] = 222; lut[ 10] = 218; lut[ 11] = 215;
        lut[ 12] = 211; lut[ 13] = 208; lut[ 14] = 205; lut[ 15] = 202;
        lut[ 16] = 199; lut[ 17] = 196; lut[ 18] = 192; lut[ 19] = 189;
        lut[ 20] = 187; lut[ 21] = 184; lut[ 22] = 181; lut[ 23] = 178;
        lut[ 24] = 175; lut[ 25] = 173; lut[ 26] = 170; lut[ 27] = 167;
        lut[ 28] = 165; lut[ 29] = 162; lut[ 30] = 160; lut[ 31] = 157;
        lut[ 32] = 155; lut[ 33] = 152; lut[ 34] = 150; lut[ 35] = 148;
        lut[ 36] = 145; lut[ 37] = 143; lut[ 38] = 141; lut[ 39] = 139;
        lut[ 40] = 136; lut[ 41] = 134; lut[ 42] = 132; lut[ 43] = 130;
        lut[ 44] = 128; lut[ 45] = 126; lut[ 46] = 124; lut[ 47] = 122;
        lut[ 48] = 120; lut[ 49] = 119; lut[ 50] = 117; lut[ 51] = 115;
        lut[ 52] = 113; lut[ 53] = 111; lut[ 54] = 110; lut[ 55] = 108;
        lut[ 56] = 106; lut[ 57] = 105; lut[ 58] = 103; lut[ 59] = 101;
        lut[ 60] = 100; lut[ 61] =  98; lut[ 62] =  97; lut[ 63] =  95;
        lut[ 64] =  94; lut[ 65] =  92; lut[ 66] =  91; lut[ 67] =  90;
        lut[ 68] =  88; lut[ 69] =  87; lut[ 70] =  85; lut[ 71] =  84;
        lut[ 72] =  83; lut[ 73] =  82; lut[ 74] =  80; lut[ 75] =  79;
        lut[ 76] =  78; lut[ 77] =  77; lut[ 78] =  75; lut[ 79] =  74;
        lut[ 80] =  73; lut[ 81] =  72; lut[ 82] =  71; lut[ 83] =  70;
        lut[ 84] =  69; lut[ 85] =  68; lut[ 86] =  67; lut[ 87] =  65;
        lut[ 88] =  64; lut[ 89] =  63; lut[ 90] =  62; lut[ 91] =  62;
        lut[ 92] =  61; lut[ 93] =  60; lut[ 94] =  59; lut[ 95] =  58;
        lut[ 96] =  57; lut[ 97] =  56; lut[ 98] =  55; lut[ 99] =  54;
        lut[100] =  53; lut[101] =  53; lut[102] =  52; lut[103] =  51;
        lut[104] =  50; lut[105] =  49; lut[106] =  49; lut[107] =  48;
        lut[108] =  47; lut[109] =  46; lut[110] =  46; lut[111] =  45;
        lut[112] =  44; lut[113] =  44; lut[114] =  43; lut[115] =  42;
        lut[116] =  42; lut[117] =  41; lut[118] =  40; lut[119] =  40;
        lut[120] =  39; lut[121] =  38; lut[122] =  38; lut[123] =  37;
        lut[124] =  37; lut[125] =  36; lut[126] =  36; lut[127] =  35;
        lut[128] =  35; lut[129] =  34; lut[130] =  33; lut[131] =  33;
        lut[132] =  32; lut[133] =  32; lut[134] =  31; lut[135] =  31;
        lut[136] =  30; lut[137] =  30; lut[138] =  30; lut[139] =  29;
        lut[140] =  29; lut[141] =  28; lut[142] =  28; lut[143] =  27;
        lut[144] =  27; lut[145] =  26; lut[146] =  26; lut[147] =  26;
        lut[148] =  25; lut[149] =  25; lut[150] =  24; lut[151] =  24;
        lut[152] =  24; lut[153] =  23; lut[154] =  23; lut[155] =  23;
        lut[156] =  22; lut[157] =  22; lut[158] =  22; lut[159] =  21;
        lut[160] =  21; lut[161] =  21; lut[162] =  20; lut[163] =  20;
        lut[164] =  20; lut[165] =  19; lut[166] =  19; lut[167] =  19;
        lut[168] =  18; lut[169] =  18; lut[170] =  18; lut[171] =  18;
        lut[172] =  17; lut[173] =  17; lut[174] =  17; lut[175] =  17;
        lut[176] =  16; lut[177] =  16; lut[178] =  16; lut[179] =  16;
        lut[180] =  15; lut[181] =  15; lut[182] =  15; lut[183] =  15;
        lut[184] =  14; lut[185] =  14; lut[186] =  14; lut[187] =  14;
        lut[188] =  14; lut[189] =  13; lut[190] =  13; lut[191] =  13;
        lut[192] =  13; lut[193] =  12; lut[194] =  12; lut[195] =  12;
        lut[196] =  12; lut[197] =  12; lut[198] =  12; lut[199] =  11;
        lut[200] =  11; lut[201] =  11; lut[202] =  11; lut[203] =  11;
        lut[204] =  11; lut[205] =  10; lut[206] =  10; lut[207] =  10;
        lut[208] =  10; lut[209] =  10; lut[210] =  10; lut[211] =   9;
        lut[212] =   9; lut[213] =   9; lut[214] =   9; lut[215] =   9;
        lut[216] =   9; lut[217] =   9; lut[218] =   8; lut[219] =   8;
        lut[220] =   8; lut[221] =   8; lut[222] =   8; lut[223] =   8;
        lut[224] =   8; lut[225] =   8; lut[226] =   7; lut[227] =   7;
        lut[228] =   7; lut[229] =   7; lut[230] =   7; lut[231] =   7;
        lut[232] =   7; lut[233] =   7; lut[234] =   7; lut[235] =   6;
        lut[236] =   6; lut[237] =   6; lut[238] =   6; lut[239] =   6;
        lut[240] =   6; lut[241] =   6; lut[242] =   6; lut[243] =   6;
        lut[244] =   6; lut[245] =   6; lut[246] =   5; lut[247] =   5;
        lut[248] =   5; lut[249] =   5; lut[250] =   5; lut[251] =   5;
        lut[252] =   5; lut[253] =   5; lut[254] =   5; lut[255] =   5;
    end

    // Convert Q8.8 input to LUT index
    // x_in is <= 0 after max-subtraction
    // index = clamp(-x_in >> 2, 0, 255)
    wire signed [15:0] neg_x = -x_in;
    wire [15:0] shifted = neg_x >>> 2;
    wire [7:0]  idx = (shifted > 16'd255) ? 8'd255 :
                      (neg_x < 0) ? 8'd0 : shifted[7:0];

    assign exp_out = lut[idx];

endmodule
