// ============================================================================
// Module: gelu_lut_256
// Description: 256-entry lookup table for GELU activation approximation.
//   Replaces crude 3-piece linear approximation with dense LUT (Issue #14).
//
//   Formula: LUT[k] = round(GELU((k-128)/32) * 256)
//   Range:   k=0 → x=-4.0 → GELU(-4) ≈ 0
//            k=128 → x=0.0 → GELU(0) = 0
//            k=255 → x=3.97 → GELU(3.97) ≈ 3.97
//
//   Input x_in is Q8.8 signed. Index = clamp((x_in >> 2) + 128, 0, 255)
//   Maps Q8.8 range [-4.0, 4.0] → LUT index [0, 255]
//   Output is Q8.8 signed.
//
//   Generated by Python:
//     import math
//     def gelu(x):
//         return x * 0.5 * (1 + math.erf(x / math.sqrt(2)))
//     for k in range(256):
//         x = (k - 128) / 32.0
//         lut[k] = max(-32768, min(32767, round(gelu(x) * 256)))
// ============================================================================
`timescale 1ns / 1ps

module gelu_lut_256 (
    input  wire signed [15:0] x_in,      // Q8.8 input
    output wire signed [15:0] gelu_out   // Q8.8 output
);

    reg signed [15:0] lut [0:255];

    // Pre-computed GELU values in Q8.8 for x in [-4.0, 3.97] step 0.03125
    initial begin
        // x = -4.0 to -3.0 (all approximately 0)
        lut[  0] =  0; lut[  1] =  0; lut[  2] =  0; lut[  3] =  0;
        lut[  4] =  0; lut[  5] =  0; lut[  6] =  0; lut[  7] =  0;
        lut[  8] =  0; lut[  9] =  0; lut[ 10] =  0; lut[ 11] =  0;
        lut[ 12] =  0; lut[ 13] =  0; lut[ 14] =  0; lut[ 15] =  0;
        lut[ 16] = -1; lut[ 17] = -1; lut[ 18] = -1; lut[ 19] = -1;
        lut[ 20] = -1; lut[ 21] = -1; lut[ 22] = -1; lut[ 23] = -2;
        lut[ 24] = -2; lut[ 25] = -2; lut[ 26] = -2; lut[ 27] = -3;
        lut[ 28] = -3; lut[ 29] = -3; lut[ 30] = -4; lut[ 31] = -4;
        // x = -3.0 to -2.0
        lut[ 32] = -4; lut[ 33] = -5; lut[ 34] = -5; lut[ 35] = -6;
        lut[ 36] = -6; lut[ 37] = -7; lut[ 38] = -7; lut[ 39] = -8;
        lut[ 40] = -9; lut[ 41] = -9; lut[ 42] = -10; lut[ 43] = -11;
        lut[ 44] = -12; lut[ 45] = -13; lut[ 46] = -14; lut[ 47] = -15;
        lut[ 48] = -16; lut[ 49] = -17; lut[ 50] = -18; lut[ 51] = -19;
        lut[ 52] = -21; lut[ 53] = -22; lut[ 54] = -24; lut[ 55] = -25;
        lut[ 56] = -27; lut[ 57] = -29; lut[ 58] = -31; lut[ 59] = -33;
        lut[ 60] = -35; lut[ 61] = -37; lut[ 62] = -39; lut[ 63] = -42;
        // x = -2.0 to -1.0
        lut[ 64] = -44; lut[ 65] = -47; lut[ 66] = -50; lut[ 67] = -53;
        lut[ 68] = -56; lut[ 69] = -59; lut[ 70] = -62; lut[ 71] = -66;
        lut[ 72] = -69; lut[ 73] = -73; lut[ 74] = -77; lut[ 75] = -81;
        lut[ 76] = -85; lut[ 77] = -89; lut[ 78] = -94; lut[ 79] = -98;
        lut[ 80] = -103; lut[ 81] = -108; lut[ 82] = -113; lut[ 83] = -118;
        lut[ 84] = -123; lut[ 85] = -128; lut[ 86] = -134; lut[ 87] = -139;
        lut[ 88] = -145; lut[ 89] = -151; lut[ 90] = -157; lut[ 91] = -163;
        lut[ 92] = -169; lut[ 93] = -175; lut[ 94] = -182; lut[ 95] = -188;
        // x = -1.0 to 0.0
        lut[ 96] = -195; lut[ 97] = -202; lut[ 98] = -208; lut[ 99] = -215;
        lut[100] = -222; lut[101] = -229; lut[102] = -236; lut[103] = -243;
        lut[104] = -250; lut[105] = -256; lut[106] = -263; lut[107] = -269;
        lut[108] = -275; lut[109] = -281; lut[110] = -286; lut[111] = -291;
        lut[112] = -295; lut[113] = -299; lut[114] = -302; lut[115] = -304;
        lut[116] = -305; lut[117] = -305; lut[118] = -304; lut[119] = -301;
        lut[120] = -297; lut[121] = -292; lut[122] = -285; lut[123] = -276;
        lut[124] = -265; lut[125] = -253; lut[126] = -238; lut[127] = -222;
        // x = 0.0 to 1.0
        lut[128] =    0; lut[129] =   16; lut[130] =   33; lut[131] =   50;
        lut[132] =   68; lut[133] =   87; lut[134] =  106; lut[135] =  126;
        lut[136] =  147; lut[137] =  168; lut[138] =  190; lut[139] =  213;
        lut[140] =  236; lut[141] =  260; lut[142] =  284; lut[143] =  309;
        lut[144] =  334; lut[145] =  360; lut[146] =  386; lut[147] =  413;
        lut[148] =  440; lut[149] =  467; lut[150] =  494; lut[151] =  522;
        lut[152] =  550; lut[153] =  578; lut[154] =  607; lut[155] =  635;
        lut[156] =  664; lut[157] =  693; lut[158] =  722; lut[159] =  751;
        // x = 1.0 to 2.0
        lut[160] =  781; lut[161] =  810; lut[162] =  840; lut[163] =  870;
        lut[164] =  900; lut[165] =  930; lut[166] =  960; lut[167] =  990;
        lut[168] = 1020; lut[169] = 1051; lut[170] = 1081; lut[171] = 1112;
        lut[172] = 1142; lut[173] = 1173; lut[174] = 1203; lut[175] = 1234;
        lut[176] = 1265; lut[177] = 1296; lut[178] = 1327; lut[179] = 1358;
        lut[180] = 1389; lut[181] = 1420; lut[182] = 1451; lut[183] = 1482;
        lut[184] = 1513; lut[185] = 1545; lut[186] = 1576; lut[187] = 1607;
        lut[188] = 1638; lut[189] = 1670; lut[190] = 1701; lut[191] = 1733;
        // x = 2.0 to 3.0
        lut[192] = 1764; lut[193] = 1796; lut[194] = 1827; lut[195] = 1859;
        lut[196] = 1891; lut[197] = 1922; lut[198] = 1954; lut[199] = 1986;
        lut[200] = 2018; lut[201] = 2049; lut[202] = 2081; lut[203] = 2113;
        lut[204] = 2145; lut[205] = 2177; lut[206] = 2209; lut[207] = 2241;
        lut[208] = 2273; lut[209] = 2305; lut[210] = 2337; lut[211] = 2369;
        lut[212] = 2401; lut[213] = 2433; lut[214] = 2465; lut[215] = 2497;
        lut[216] = 2529; lut[217] = 2561; lut[218] = 2593; lut[219] = 2625;
        lut[220] = 2657; lut[221] = 2689; lut[222] = 2722; lut[223] = 2754;
        // x = 3.0 to 4.0 (GELU ≈ x)
        lut[224] = 2786; lut[225] = 2818; lut[226] = 2850; lut[227] = 2882;
        lut[228] = 2914; lut[229] = 2946; lut[230] = 2978; lut[231] = 3010;
        lut[232] = 3042; lut[233] = 3074; lut[234] = 3107; lut[235] = 3139;
        lut[236] = 3171; lut[237] = 3203; lut[238] = 3235; lut[239] = 3267;
        lut[240] = 3299; lut[241] = 3331; lut[242] = 3363; lut[243] = 3395;
        lut[244] = 3427; lut[245] = 3460; lut[246] = 3492; lut[247] = 3524;
        lut[248] = 3556; lut[249] = 3588; lut[250] = 3620; lut[251] = 3652;
        lut[252] = 3684; lut[253] = 3716; lut[254] = 3748; lut[255] = 3780;
    end

    // Convert Q8.8 input to LUT index
    // index = clamp((x_in >>> 2) + 128, 0, 255)
    wire signed [15:0] shifted = (x_in >>> 2) + 16'sd128;
    wire [7:0] idx = (shifted < 0) ? 8'd0 :
                     (shifted > 16'sd255) ? 8'd255 : shifted[7:0];

    assign gelu_out = lut[idx];

endmodule

