// ============================================================================
// Module: inv_sqrt_lut_256
// Description: 256-entry lookup table for 1/sqrt(x) approximation.
//   Used by layer_norm for computing the inverse standard deviation.
//
//   Formula: LUT[k] = round(256 / sqrt((k+1)/16))
//   Range:   k=0 → 1/sqrt(0.0625) = 4.0 → 1024 (clamped to 512)
//            k=255 → 1/sqrt(16.0) = 0.25 → 64
//
//   The input var_in is Q8.8 unsigned variance (expected > 0).
//   Index = clamp(var_in >> 2, 0, 255)
//   This maps Q8.8 variance range [0, 64] → LUT index [0, 255]
//
//   Output is Q8.8 representing 1/sqrt(variance).
//   Replaces the crude 5-bucket step function (Issue #3/#7).
//
//   Generated by Python:
//     import math
//     for k in range(256):
//         val = 256.0 / math.sqrt((k+1) / 16.0)
//         lut[k] = max(16, min(4096, round(val)))
// ============================================================================
module inv_sqrt_lut_256 (
    input  wire [15:0]        var_in,    // Q8.8 variance (unsigned, > 0)
    output reg  signed [15:0] inv_sqrt_out  // Q8.8 result: 1/sqrt(var)
);

    reg [15:0] lut [0:255];

    // Generated by: round(256 / sqrt((k+1)/16)) for k=0..255
    // Represents 1/sqrt(var) in Q8.8 for var from ~0.06 to ~16.0
    initial begin
        lut[  0] = 1024; lut[  1] =  724; lut[  2] =  591; lut[  3] =  512;
        lut[  4] =  458; lut[  5] =  418; lut[  6] =  387; lut[  7] =  362;
        lut[  8] =  341; lut[  9] =  323; lut[ 10] =  308; lut[ 11] =  295;
        lut[ 12] =  284; lut[ 13] =  274; lut[ 14] =  265; lut[ 15] =  256;
        lut[ 16] =  248; lut[ 17] =  241; lut[ 18] =  234; lut[ 19] =  228;
        lut[ 20] =  223; lut[ 21] =  218; lut[ 22] =  213; lut[ 23] =  209;
        lut[ 24] =  204; lut[ 25] =  200; lut[ 26] =  196; lut[ 27] =  193;
        lut[ 28] =  190; lut[ 29] =  186; lut[ 30] =  183; lut[ 31] =  181;
        lut[ 32] =  178; lut[ 33] =  175; lut[ 34] =  173; lut[ 35] =  170;
        lut[ 36] =  168; lut[ 37] =  166; lut[ 38] =  163; lut[ 39] =  161;
        lut[ 40] =  159; lut[ 41] =  157; lut[ 42] =  156; lut[ 43] =  154;
        lut[ 44] =  152; lut[ 45] =  150; lut[ 46] =  149; lut[ 47] =  147;
        lut[ 48] =  145; lut[ 49] =  144; lut[ 50] =  142; lut[ 51] =  141;
        lut[ 52] =  140; lut[ 53] =  138; lut[ 54] =  137; lut[ 55] =  136;
        lut[ 56] =  134; lut[ 57] =  133; lut[ 58] =  132; lut[ 59] =  131;
        lut[ 60] =  130; lut[ 61] =  129; lut[ 62] =  128; lut[ 63] =  127;
        lut[ 64] =  126; lut[ 65] =  125; lut[ 66] =  124; lut[ 67] =  123;
        lut[ 68] =  122; lut[ 69] =  121; lut[ 70] =  120; lut[ 71] =  119;
        lut[ 72] =  118; lut[ 73] =  118; lut[ 74] =  117; lut[ 75] =  116;
        lut[ 76] =  115; lut[ 77] =  115; lut[ 78] =  114; lut[ 79] =  113;
        lut[ 80] =  113; lut[ 81] =  112; lut[ 82] =  111; lut[ 83] =  111;
        lut[ 84] =  110; lut[ 85] =  110; lut[ 86] =  109; lut[ 87] =  108;
        lut[ 88] =  108; lut[ 89] =  107; lut[ 90] =  107; lut[ 91] =  106;
        lut[ 92] =  106; lut[ 93] =  105; lut[ 94] =  105; lut[ 95] =  104;
        lut[ 96] =  104; lut[ 97] =  103; lut[ 98] =  103; lut[ 99] =  102;
        lut[100] =  102; lut[101] =  101; lut[102] =  101; lut[103] =  101;
        lut[104] =  100; lut[105] =  100; lut[106] =   99; lut[107] =   99;
        lut[108] =   99; lut[109] =   98; lut[110] =   98; lut[111] =   97;
        lut[112] =   97; lut[113] =   97; lut[114] =   96; lut[115] =   96;
        lut[116] =   96; lut[117] =   95; lut[118] =   95; lut[119] =   95;
        lut[120] =   94; lut[121] =   94; lut[122] =   94; lut[123] =   93;
        lut[124] =   93; lut[125] =   93; lut[126] =   92; lut[127] =   92;
        lut[128] =   92; lut[129] =   91; lut[130] =   91; lut[131] =   91;
        lut[132] =   91; lut[133] =   90; lut[134] =   90; lut[135] =   90;
        lut[136] =   89; lut[137] =   89; lut[138] =   89; lut[139] =   89;
        lut[140] =   88; lut[141] =   88; lut[142] =   88; lut[143] =   88;
        lut[144] =   87; lut[145] =   87; lut[146] =   87; lut[147] =   87;
        lut[148] =   86; lut[149] =   86; lut[150] =   86; lut[151] =   86;
        lut[152] =   85; lut[153] =   85; lut[154] =   85; lut[155] =   85;
        lut[156] =   84; lut[157] =   84; lut[158] =   84; lut[159] =   84;
        lut[160] =   84; lut[161] =   83; lut[162] =   83; lut[163] =   83;
        lut[164] =   83; lut[165] =   82; lut[166] =   82; lut[167] =   82;
        lut[168] =   82; lut[169] =   82; lut[170] =   81; lut[171] =   81;
        lut[172] =   81; lut[173] =   81; lut[174] =   81; lut[175] =   80;
        lut[176] =   80; lut[177] =   80; lut[178] =   80; lut[179] =   80;
        lut[180] =   79; lut[181] =   79; lut[182] =   79; lut[183] =   79;
        lut[184] =   79; lut[185] =   79; lut[186] =   78; lut[187] =   78;
        lut[188] =   78; lut[189] =   78; lut[190] =   78; lut[191] =   77;
        lut[192] =   77; lut[193] =   77; lut[194] =   77; lut[195] =   77;
        lut[196] =   77; lut[197] =   76; lut[198] =   76; lut[199] =   76;
        lut[200] =   76; lut[201] =   76; lut[202] =   76; lut[203] =   76;
        lut[204] =   75; lut[205] =   75; lut[206] =   75; lut[207] =   75;
        lut[208] =   75; lut[209] =   75; lut[210] =   74; lut[211] =   74;
        lut[212] =   74; lut[213] =   74; lut[214] =   74; lut[215] =   74;
        lut[216] =   74; lut[217] =   73; lut[218] =   73; lut[219] =   73;
        lut[220] =   73; lut[221] =   73; lut[222] =   73; lut[223] =   73;
        lut[224] =   72; lut[225] =   72; lut[226] =   72; lut[227] =   72;
        lut[228] =   72; lut[229] =   72; lut[230] =   72; lut[231] =   72;
        lut[232] =   71; lut[233] =   71; lut[234] =   71; lut[235] =   71;
        lut[236] =   71; lut[237] =   71; lut[238] =   71; lut[239] =   71;
        lut[240] =   70; lut[241] =   70; lut[242] =   70; lut[243] =   70;
        lut[244] =   70; lut[245] =   70; lut[246] =   70; lut[247] =   70;
        lut[248] =   69; lut[249] =   69; lut[250] =   69; lut[251] =   69;
        lut[252] =   69; lut[253] =   69; lut[254] =   69; lut[255] =   69;
    end

    // Convert Q8.8 variance to LUT index
    // index = clamp(var_in >> 2, 0, 255)
    wire [15:0] shifted = var_in >> 2;
    wire [7:0]  idx = (shifted > 16'd255) ? 8'd255 :
                      (var_in == 16'd0) ? 8'd0 : shifted[7:0];

    always @(*) begin
        inv_sqrt_out = $signed(lut[idx]);
    end

endmodule

