`timescale 1ns/1ps

module sentence_cosim_tb;
  parameter VOCAB_SIZE  = 16;
  parameter MAX_SEQ_LEN = 8;
  parameter EMBED_DIM   = 4;
  parameter NUM_HEADS   = 2;
  parameter HEAD_DIM    = 2;
  parameter FFN_DIM     = 8;
  parameter NUM_LAYERS  = 2;
  parameter DATA_WIDTH  = 16;

  reg clk, rst;
  reg valid_in;
  reg [3:0] token_in;
  reg [2:0] position_in;
  reg load_token_emb, load_pos_emb;
  reg [3:0] load_token_idx;
  reg [1:0] load_dim_idx;
  reg signed [15:0] load_emb_data;
  reg [2:0] load_pos_idx;
  reg load_ln_en;
  reg [1:0] load_layer_idx;
  reg load_ln_sel, load_ln_is_gamma;
  reg [1:0] load_ln_dim;
  reg signed [15:0] load_ln_data;
  reg load_attn_weight_en;
  reg [1:0] load_attn_matrix_sel;
  reg [1:0] load_attn_row, load_attn_col;
  reg signed [15:0] load_attn_data;
  reg load_ffn_weight_en;
  reg load_ffn_layer_sel, load_ffn_is_bias;
  reg [2:0] load_ffn_row, load_ffn_col;
  reg signed [15:0] load_ffn_data;
  wire [3:0] token_out;
  wire [63:0] logits_out;
  wire valid_out;
  integer cycle_count;
  integer total_cycles;
  integer token_count;
  integer idx, row_idx, col_idx, layer_idx_i;

  gpt2_engine #(
    .VOCAB_SIZE(VOCAB_SIZE), .MAX_SEQ_LEN(MAX_SEQ_LEN),
    .EMBED_DIM(EMBED_DIM), .NUM_HEADS(NUM_HEADS),
    .HEAD_DIM(HEAD_DIM), .FFN_DIM(FFN_DIM),
    .NUM_LAYERS(NUM_LAYERS), .DATA_WIDTH(DATA_WIDTH)
  ) dut (
    .clk(clk), .rst(rst),
    .load_token_emb(load_token_emb), .load_token_idx(load_token_idx),
    .load_dim_idx(load_dim_idx), .load_emb_data(load_emb_data),
    .load_pos_emb(load_pos_emb), .load_pos_idx(load_pos_idx),
    .load_ln_en(load_ln_en), .load_layer_idx(load_layer_idx),
    .load_ln_sel(load_ln_sel), .load_ln_is_gamma(load_ln_is_gamma),
    .load_ln_dim(load_ln_dim), .load_ln_data(load_ln_data),
    .load_attn_weight_en(load_attn_weight_en),
    .load_attn_matrix_sel(load_attn_matrix_sel),
    .load_attn_row(load_attn_row), .load_attn_col(load_attn_col),
    .load_attn_data(load_attn_data),
    .load_ffn_weight_en(load_ffn_weight_en),
    .load_ffn_layer_sel(load_ffn_layer_sel),
    .load_ffn_is_bias(load_ffn_is_bias),
    .load_ffn_row(load_ffn_row), .load_ffn_col(load_ffn_col),
    .load_ffn_data(load_ffn_data),
    .valid_in(valid_in), .token_in(token_in),
    .position_in(position_in),
    .token_out(token_out), .logits_out(logits_out),
    .valid_out(valid_out),
    .total_zero_skips(), .total_cycles()
  );

  always #5 clk = ~clk;

  initial begin
    $dumpfile("sentence_cosim.vcd");
    $dumpvars(0, sentence_cosim_tb);
  end

  initial begin
    clk = 0; rst = 1;
    valid_in = 0; load_token_emb = 0; load_pos_emb = 0;
    token_in = 0; position_in = 0;
    load_token_idx = 0; load_dim_idx = 0; load_emb_data = 0;
    load_pos_idx = 0;
    load_ln_en = 0; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 0; load_ln_data = 0;
    load_attn_weight_en = 0; load_attn_matrix_sel = 0; load_attn_row = 0; load_attn_col = 0; load_attn_data = 0;
    load_ffn_weight_en = 0; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 0; load_ffn_data = 0;
    total_cycles = 0; token_count = 0;

    // ===== REAL GPT-2 WEIGHTS (Q8.8) =====
    #35 rst = 0; #25;

    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 0; load_ln_data = 16'h0039;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 0; load_ln_data = 16'hffff;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 0; load_ln_data = 16'h0022;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 0; load_ln_data = 16'h000b;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 1; load_ln_data = 16'h002f;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 1; load_ln_data = 16'h0007;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 1; load_ln_data = 16'h0036;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 1; load_ln_data = 16'h0008;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 2; load_ln_data = 16'h0027;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 2; load_ln_data = 16'hfff0;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 2; load_ln_data = 16'h0035;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 2; load_ln_data = 16'h0001;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 3; load_ln_data = 16'h0031;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 3; load_ln_data = 16'hffff;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 3; load_ln_data = 16'h0141;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 0; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 3; load_ln_data = 16'h0004;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 0; load_ln_data = 16'h0039;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 0; load_ln_data = 16'hffff;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 0; load_ln_data = 16'h0022;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 0; load_ln_data = 16'h000b;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 1; load_ln_data = 16'h002f;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 1; load_ln_data = 16'h0007;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 1; load_ln_data = 16'h0036;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 1; load_ln_data = 16'h0008;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 2; load_ln_data = 16'h0027;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 2; load_ln_data = 16'hfff0;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 2; load_ln_data = 16'h0035;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 2; load_ln_data = 16'h0001;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 3; load_ln_data = 16'h0031;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 3; load_ln_data = 16'hffff;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 1; load_ln_dim = 3; load_ln_data = 16'h0141;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 1; load_ln_sel = 1; load_ln_is_gamma = 0; load_ln_dim = 3; load_ln_data = 16'h0004;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 0; load_ln_data = 16'h0166;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 0; load_ln_data = 16'h0000;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 1; load_ln_data = 16'h0160;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 1; load_ln_data = 16'h0009;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 2; load_ln_data = 16'h01e3;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 2; load_ln_data = 16'hffef;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 1; load_ln_dim = 3; load_ln_data = 16'h012b;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_ln_en = 1; load_layer_idx = 2; load_ln_sel = 0; load_ln_is_gamma = 0; load_ln_dim = 3; load_ln_data = 16'h0000;
    @(negedge clk); load_ln_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 0; load_attn_col = 0; load_attn_data = 16'hff87;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 0; load_attn_col = 0; load_attn_data = 16'h0039;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 0; load_attn_col = 0; load_attn_data = 16'hffd0;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 0; load_attn_col = 0; load_attn_data = 16'h0050;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 0; load_attn_col = 1; load_attn_data = 16'hffbd;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 0; load_attn_col = 1; load_attn_data = 16'hfff5;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 0; load_attn_col = 1; load_attn_data = 16'h002f;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 0; load_attn_col = 1; load_attn_data = 16'hffd0;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 0; load_attn_col = 2; load_attn_data = 16'hffe7;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 0; load_attn_col = 2; load_attn_data = 16'h006b;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 0; load_attn_col = 2; load_attn_data = 16'hff6b;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 0; load_attn_col = 2; load_attn_data = 16'h0019;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 0; load_attn_col = 3; load_attn_data = 16'hffa6;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 0; load_attn_col = 3; load_attn_data = 16'h002d;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 0; load_attn_col = 3; load_attn_data = 16'hfffa;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 0; load_attn_col = 3; load_attn_data = 16'hfff8;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 1; load_attn_col = 0; load_attn_data = 16'h0016;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 1; load_attn_col = 0; load_attn_data = 16'h00a6;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 1; load_attn_col = 0; load_attn_data = 16'hfff8;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 1; load_attn_col = 0; load_attn_data = 16'hffc1;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 1; load_attn_col = 1; load_attn_data = 16'h0026;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 1; load_attn_col = 1; load_attn_data = 16'h002b;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 1; load_attn_col = 1; load_attn_data = 16'h0069;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 1; load_attn_col = 1; load_attn_data = 16'hffcd;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 1; load_attn_col = 2; load_attn_data = 16'h003d;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 1; load_attn_col = 2; load_attn_data = 16'hfff0;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 1; load_attn_col = 2; load_attn_data = 16'h0014;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 1; load_attn_col = 2; load_attn_data = 16'hffe4;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 1; load_attn_col = 3; load_attn_data = 16'h004a;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 1; load_attn_col = 3; load_attn_data = 16'h0068;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 1; load_attn_col = 3; load_attn_data = 16'h002b;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 1; load_attn_col = 3; load_attn_data = 16'h0009;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 2; load_attn_col = 0; load_attn_data = 16'h0001;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 2; load_attn_col = 0; load_attn_data = 16'hffda;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 2; load_attn_col = 0; load_attn_data = 16'h0010;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 2; load_attn_col = 0; load_attn_data = 16'hff92;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 2; load_attn_col = 1; load_attn_data = 16'h0012;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 2; load_attn_col = 1; load_attn_data = 16'h0005;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 2; load_attn_col = 1; load_attn_data = 16'h0038;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 2; load_attn_col = 1; load_attn_data = 16'h0028;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 2; load_attn_col = 2; load_attn_data = 16'h005e;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 2; load_attn_col = 2; load_attn_data = 16'hffe8;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 2; load_attn_col = 2; load_attn_data = 16'hfff7;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 2; load_attn_col = 2; load_attn_data = 16'h000e;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 2; load_attn_col = 3; load_attn_data = 16'hffed;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 2; load_attn_col = 3; load_attn_data = 16'hffde;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 2; load_attn_col = 3; load_attn_data = 16'hffd1;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 2; load_attn_col = 3; load_attn_data = 16'hfffe;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 3; load_attn_col = 0; load_attn_data = 16'h0039;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 3; load_attn_col = 0; load_attn_data = 16'h0040;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 3; load_attn_col = 0; load_attn_data = 16'h0019;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 3; load_attn_col = 0; load_attn_data = 16'h000b;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 3; load_attn_col = 1; load_attn_data = 16'hffd0;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 3; load_attn_col = 1; load_attn_data = 16'hffb0;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 3; load_attn_col = 1; load_attn_data = 16'h0019;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 3; load_attn_col = 1; load_attn_data = 16'hfffa;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 3; load_attn_col = 2; load_attn_data = 16'hfffc;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 3; load_attn_col = 2; load_attn_data = 16'h0024;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 3; load_attn_col = 2; load_attn_data = 16'hfffd;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 3; load_attn_col = 2; load_attn_data = 16'h0031;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd0; load_attn_row = 3; load_attn_col = 3; load_attn_data = 16'h006d;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd1; load_attn_row = 3; load_attn_col = 3; load_attn_data = 16'h0049;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd2; load_attn_row = 3; load_attn_col = 3; load_attn_data = 16'h0042;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_attn_weight_en = 1; load_attn_matrix_sel = 2'd3; load_attn_row = 3; load_attn_col = 3; load_attn_data = 16'h0000;
    @(negedge clk); load_attn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 0; load_ffn_data = 16'h0018;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 1; load_ffn_data = 16'h0019;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 2; load_ffn_data = 16'hfff8;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 3; load_ffn_data = 16'h0011;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 4; load_ffn_data = 16'hffe2;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 5; load_ffn_data = 16'h0001;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 6; load_ffn_data = 16'h0001;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 7; load_ffn_data = 16'hffdd;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 0; load_ffn_data = 16'hffe0;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 1; load_ffn_data = 16'hffef;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 2; load_ffn_data = 16'h0008;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 3; load_ffn_data = 16'hfffd;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 4; load_ffn_data = 16'hfff4;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 5; load_ffn_data = 16'hffff;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 6; load_ffn_data = 16'h0016;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 7; load_ffn_data = 16'hffea;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 0; load_ffn_data = 16'h000d;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 1; load_ffn_data = 16'hfff6;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 2; load_ffn_data = 16'hfff4;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 3; load_ffn_data = 16'hffff;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 4; load_ffn_data = 16'h0020;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 5; load_ffn_data = 16'h0023;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 6; load_ffn_data = 16'h002a;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 7; load_ffn_data = 16'hfffd;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 0; load_ffn_data = 16'hfffd;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 1; load_ffn_data = 16'h0028;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 2; load_ffn_data = 16'h0041;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 3; load_ffn_data = 16'hffda;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 4; load_ffn_data = 16'h0045;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 5; load_ffn_data = 16'hffd2;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 6; load_ffn_data = 16'hffbe;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 7; load_ffn_data = 16'hffe7;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 0; load_ffn_data = 16'h000a;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 1; load_ffn_data = 16'hffe9;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 2; load_ffn_data = 16'hffdc;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 3; load_ffn_data = 16'hfff8;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 4; load_ffn_data = 16'hfffc;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 5; load_ffn_data = 16'hfffc;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 6; load_ffn_data = 16'hffcd;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 0; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 7; load_ffn_data = 16'h0020;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 0; load_ffn_data = 16'hffe5;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 1; load_ffn_data = 16'h0027;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 2; load_ffn_data = 16'h0008;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 0; load_ffn_col = 3; load_ffn_data = 16'h0006;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 0; load_ffn_data = 16'h0009;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 1; load_ffn_data = 16'hfff1;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 2; load_ffn_data = 16'h0016;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 1; load_ffn_col = 3; load_ffn_data = 16'hfffd;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 0; load_ffn_data = 16'hffec;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 1; load_ffn_data = 16'h0002;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 2; load_ffn_data = 16'hffe8;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 2; load_ffn_col = 3; load_ffn_data = 16'h0011;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 0; load_ffn_data = 16'h0018;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 1; load_ffn_data = 16'h0008;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 2; load_ffn_data = 16'h000c;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 3; load_ffn_col = 3; load_ffn_data = 16'h0010;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 4; load_ffn_col = 0; load_ffn_data = 16'hfff6;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 4; load_ffn_col = 1; load_ffn_data = 16'h0012;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 4; load_ffn_col = 2; load_ffn_data = 16'h0011;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 4; load_ffn_col = 3; load_ffn_data = 16'hffe6;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 5; load_ffn_col = 0; load_ffn_data = 16'hffe5;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 5; load_ffn_col = 1; load_ffn_data = 16'h0006;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 5; load_ffn_col = 2; load_ffn_data = 16'h000a;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 5; load_ffn_col = 3; load_ffn_data = 16'hfff7;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 6; load_ffn_col = 0; load_ffn_data = 16'h0025;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 6; load_ffn_col = 1; load_ffn_data = 16'hfff9;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 6; load_ffn_col = 2; load_ffn_data = 16'h0009;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 6; load_ffn_col = 3; load_ffn_data = 16'hffe2;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 7; load_ffn_col = 0; load_ffn_data = 16'hffed;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 7; load_ffn_col = 1; load_ffn_data = 16'h0011;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 7; load_ffn_col = 2; load_ffn_data = 16'h000a;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 0; load_ffn_row = 7; load_ffn_col = 3; load_ffn_data = 16'hffea;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 0; load_ffn_data = 16'h000c;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 1; load_ffn_data = 16'h0008;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 2; load_ffn_data = 16'hffe9;
    @(negedge clk); load_ffn_weight_en = 0;
    @(negedge clk); load_ffn_weight_en = 1; load_ffn_layer_sel = 1; load_ffn_is_bias = 1; load_ffn_row = 0; load_ffn_col = 3; load_ffn_data = 16'hfffe;
    @(negedge clk); load_ffn_weight_en = 0;

    // ===== LOAD EMBEDDINGS =====
    @(negedge clk); load_token_emb = 1; load_token_idx = 0; load_dim_idx = 0; load_emb_data = 16'hffe4;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 0; load_dim_idx = 1; load_emb_data = 16'hfff6;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 0; load_dim_idx = 2; load_emb_data = 16'h0008;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 0; load_dim_idx = 3; load_emb_data = 16'h0022;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 1; load_dim_idx = 0; load_emb_data = 16'h000a;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 1; load_dim_idx = 1; load_emb_data = 16'hfff4;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 1; load_dim_idx = 2; load_emb_data = 16'h000c;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 1; load_dim_idx = 3; load_emb_data = 16'hffe7;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 2; load_dim_idx = 0; load_emb_data = 16'hffdf;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 2; load_dim_idx = 1; load_emb_data = 16'h000c;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 2; load_dim_idx = 2; load_emb_data = 16'h002f;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 2; load_dim_idx = 3; load_emb_data = 16'hffe9;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 3; load_dim_idx = 0; load_emb_data = 16'hffe8;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 3; load_dim_idx = 1; load_emb_data = 16'hffb2;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 3; load_dim_idx = 2; load_emb_data = 16'h0036;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 3; load_dim_idx = 3; load_emb_data = 16'hfff5;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 4; load_dim_idx = 0; load_emb_data = 16'hfff3;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 4; load_dim_idx = 1; load_emb_data = 16'hffe4;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 4; load_dim_idx = 2; load_emb_data = 16'h001b;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 4; load_dim_idx = 3; load_emb_data = 16'hffe6;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 5; load_dim_idx = 0; load_emb_data = 16'h0003;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 5; load_dim_idx = 1; load_emb_data = 16'hffd9;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 5; load_dim_idx = 2; load_emb_data = 16'h0031;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 5; load_dim_idx = 3; load_emb_data = 16'h0003;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 6; load_dim_idx = 0; load_emb_data = 16'hffeb;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 6; load_dim_idx = 1; load_emb_data = 16'h0008;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 6; load_dim_idx = 2; load_emb_data = 16'h0012;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 6; load_dim_idx = 3; load_emb_data = 16'hffd9;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 7; load_dim_idx = 0; load_emb_data = 16'hffdf;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 7; load_dim_idx = 1; load_emb_data = 16'hffca;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 7; load_dim_idx = 2; load_emb_data = 16'h0022;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 7; load_dim_idx = 3; load_emb_data = 16'h0016;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 8; load_dim_idx = 0; load_emb_data = 16'hffec;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 8; load_dim_idx = 1; load_emb_data = 16'hffe0;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 8; load_dim_idx = 2; load_emb_data = 16'h000e;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 8; load_dim_idx = 3; load_emb_data = 16'h0014;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 9; load_dim_idx = 0; load_emb_data = 16'hfff6;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 9; load_dim_idx = 1; load_emb_data = 16'h000d;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 9; load_dim_idx = 2; load_emb_data = 16'h001f;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 9; load_dim_idx = 3; load_emb_data = 16'hfff1;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 10; load_dim_idx = 0; load_emb_data = 16'hfff6;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 10; load_dim_idx = 1; load_emb_data = 16'hffe5;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 10; load_dim_idx = 2; load_emb_data = 16'h001b;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 10; load_dim_idx = 3; load_emb_data = 16'hffd8;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 11; load_dim_idx = 0; load_emb_data = 16'h0003;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 11; load_dim_idx = 1; load_emb_data = 16'hffff;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 11; load_dim_idx = 2; load_emb_data = 16'h0008;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 11; load_dim_idx = 3; load_emb_data = 16'h000e;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 12; load_dim_idx = 0; load_emb_data = 16'h0010;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 12; load_dim_idx = 1; load_emb_data = 16'hfffc;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 12; load_dim_idx = 2; load_emb_data = 16'h000e;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 12; load_dim_idx = 3; load_emb_data = 16'hffe9;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 13; load_dim_idx = 0; load_emb_data = 16'h000c;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 13; load_dim_idx = 1; load_emb_data = 16'hfffd;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 13; load_dim_idx = 2; load_emb_data = 16'h0007;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 13; load_dim_idx = 3; load_emb_data = 16'h000c;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 14; load_dim_idx = 0; load_emb_data = 16'hfff8;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 14; load_dim_idx = 1; load_emb_data = 16'hffdd;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 14; load_dim_idx = 2; load_emb_data = 16'h000a;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 14; load_dim_idx = 3; load_emb_data = 16'h002d;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 15; load_dim_idx = 0; load_emb_data = 16'hffef;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 15; load_dim_idx = 1; load_emb_data = 16'hfffc;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 15; load_dim_idx = 2; load_emb_data = 16'h0010;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_token_emb = 1; load_token_idx = 15; load_dim_idx = 3; load_emb_data = 16'hfff7;
    @(negedge clk); load_token_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 0; load_dim_idx = 0; load_emb_data = 16'hfffb;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 0; load_dim_idx = 1; load_emb_data = 16'hffcd;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 0; load_dim_idx = 2; load_emb_data = 16'h0001;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 0; load_dim_idx = 3; load_emb_data = 16'h0003;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 1; load_dim_idx = 0; load_emb_data = 16'h0006;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 1; load_dim_idx = 1; load_emb_data = 16'hfff2;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 1; load_dim_idx = 2; load_emb_data = 16'hffe8;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 1; load_dim_idx = 3; load_emb_data = 16'hfffd;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 2; load_dim_idx = 0; load_emb_data = 16'h0001;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 2; load_dim_idx = 1; load_emb_data = 16'hffea;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 2; load_dim_idx = 2; load_emb_data = 16'h000e;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 2; load_dim_idx = 3; load_emb_data = 16'hffff;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 3; load_dim_idx = 0; load_emb_data = 16'h0000;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 3; load_dim_idx = 1; load_emb_data = 16'hffed;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 3; load_dim_idx = 2; load_emb_data = 16'h001b;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 3; load_dim_idx = 3; load_emb_data = 16'h0000;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 4; load_dim_idx = 0; load_emb_data = 16'h0002;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 4; load_dim_idx = 1; load_emb_data = 16'hfffa;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 4; load_dim_idx = 2; load_emb_data = 16'h0021;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 4; load_dim_idx = 3; load_emb_data = 16'hfffe;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 5; load_dim_idx = 0; load_emb_data = 16'h0002;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 5; load_dim_idx = 1; load_emb_data = 16'hfff7;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 5; load_dim_idx = 2; load_emb_data = 16'h0022;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 5; load_dim_idx = 3; load_emb_data = 16'hffff;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 6; load_dim_idx = 0; load_emb_data = 16'h0001;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 6; load_dim_idx = 1; load_emb_data = 16'hfffb;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 6; load_dim_idx = 2; load_emb_data = 16'h001f;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 6; load_dim_idx = 3; load_emb_data = 16'hffff;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 7; load_dim_idx = 0; load_emb_data = 16'h0001;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 7; load_dim_idx = 1; load_emb_data = 16'hffff;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 7; load_dim_idx = 2; load_emb_data = 16'h001e;
    @(negedge clk); load_pos_emb = 0;
    @(negedge clk); load_pos_emb = 1; load_pos_idx = 7; load_dim_idx = 3; load_emb_data = 16'hffff;
    @(negedge clk); load_pos_emb = 0;
    #20;

    $display("");
    $display("+=========================================================+");
    $display("|  BitbyBit GPU -- Sentence Processing Cosimulation        |");
    $display("|  Model: Real GPT-2 (Q8.8 quantized)                     |");
    $display("|  Tokens: [1]");
    $display("|  Sequence length: 1 tokens                                 |");
    $display("+=========================================================+");
    $display("");

    // ===== TOKEN 0: id=1 =====
    @(negedge clk);
    token_in = 1; position_in = 0;
    valid_in = 1;
    @(negedge clk); valid_in = 0;
    cycle_count = 0;
    while (!valid_out && cycle_count < 1000) begin
      @(negedge clk); cycle_count = cycle_count + 1;
    end

    if (valid_out) begin
      total_cycles = total_cycles + cycle_count;
      token_count = token_count + 1;
      $display("TOKEN pos=%0d id=%0d predicted=%0d cycles=%0d logits=%h",
               0, 1, token_out, cycle_count, logits_out);
      $display("  LOGIT pos=%0d dim=%0d hex=%h",
               0, 0, logits_out[0 +: 16]);
      $display("  LOGIT pos=%0d dim=%0d hex=%h",
               0, 1, logits_out[16 +: 16]);
      $display("  LOGIT pos=%0d dim=%0d hex=%h",
               0, 2, logits_out[32 +: 16]);
      $display("  LOGIT pos=%0d dim=%0d hex=%h",
               0, 3, logits_out[48 +: 16]);
    end else begin
      $display("TOKEN pos=%0d id=%0d TIMEOUT", 0, 1);
    end
    repeat(5) @(negedge clk);

    $display("");
    $display("SUMMARY total_tokens=%0d total_cycles=%0d", token_count, total_cycles);
    $display("DONE");
    $finish;
  end
endmodule
